# Generated by Django 3.1.7 on 2021-07-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('ANDROID', 'ANDROID'), ('IOS', 'IOS'), ('FLUTTER', 'FLUTTER'), ('REACT-N', 'REACT-N'), ('DESKTOP', 'DESKTOP'), ('FULLSTACK', 'FULLSTACK')], default='FRONTEND', max_length=10)),
                ('block', models.CharField(choices=[('HTML/CSS', 'HTML/CSS'), ('JS/REACT', 'JS/REACT'), ('PYTHON/DJANGO', 'PYTHON/DJANGO'), ('PHP/LARAVEL', 'PHP/LARAVEL'), ('KOTLIN/ANDROID', 'KOTLIN/ANDROID'), ('SWIFT/IOS', 'SWIFT/IOS'), ('DART/FLUTTER', 'DART/FLUTTER'), ('JS/REACT-N', 'JS/REACT-N'), ('C#/DESKTOP', 'C#/DESKTOP')], default='HTML/CSS', max_length=16)),
                ('name', models.CharField(max_length=50)),
                ('student_qty', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('EMPTY', 'EMPTY'), ('PART', 'PART'), ('FULL', 'FULL')], default='EMPTY', max_length=16)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.mentor')),
            ],
        ),
    ]
