# Generated by Django 3.1.7 on 2021-07-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='language',
            field=models.CharField(choices=[('UZ', 'UZ'), ('RU', 'RU'), ('ENG', 'ENG')], default='UZ', max_length=4),
        ),
        migrations.AddField(
            model_name='group',
            name='time',
            field=models.CharField(choices=[('11:00-12:30', '11:00-12:30'), ('14:00-15:30', '14:00-15:30'), ('16:00-17:30', '16:00-17:30'), ('18:00-19:30', '18:00-19:30')], default='11:00-12:30', max_length=12),
        ),
    ]
