# Generated by Django 3.1.7 on 2021-08-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
